### ISSUE TITLE
Unresolved Dependency

### ISSUE THREAD

**Issue by obarat** [carlos-sancho-ramirez/android-scala-langbook#1]
Hi,

I am getting the below error when i execute sbt android:compile

`[error] (root/*:update) sbt.ResolveException: unresolved dependency: generic#generic_2.11;0.1-SNAPSHOT: not found`

**Comment by carlos-sancho-ramirez** [comment]
Hi,

android-scala-langbook repository uses generic-scala-langbook repository as submodule. If it cannot be resolved, my guess is that only android-scala-langbook was cloned. Try cloning it recursively instead and compile again.

$ git clone --recursive https://github.com/carlos-sancho-ramirez/android-scala-langbook.git

The above command should clone both repos. I should update the readme file to avoid confusing other developers. Thanks for the hint.
